version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jadwal_sholat
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/jadwal-sholat/node_modules
      - /app/packages/eslint-config-custom/node_modules
      - /app/apps/jadwal-sholat/.next
    environment:
      - NEXT_PUBLIC_QURAN_API=${NEXT_PUBLIC_QURAN_API}
      - NEXT_PUBLIC_PUASA_SUNNAH_API=${NEXT_PUBLIC_PUASA_SUNNAH_API}
      - NEXT_PUBLIC_JADWAL_SHOLAT_API=${NEXT_PUBLIC_JADWAL_SHOLAT_API}
      - NEXT_PUBLIC_ASMAUL_HUSNA_API=${NEXT_PUBLIC_ASMAUL_HUSNA_API}
      - NEXT_PUBLIC_DOA_HARIAN_API=${NEXT_PUBLIC_DOA_HARIAN_API}
